# Generated by Django 5.1.6 on 2026-10-05 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='otp',
            field=models.CharField(max_length=4),
        ),
    ]
