# Generated by Django 5.1.6 on 2026-10-07 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_uniqueid',
            field=models.CharField(default=0, max_length=50, unique=True),
        ),
    ]
