# Generated by Django 5.1.6 on 2026-10-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_company_company_uniqueid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='gst_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
