# Generated by Django 5.1.6 on 2026-10-07 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_alter_company_gst_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_type', models.CharField(choices=[('ivyis', 'IVYIS'), ('other', 'Other Company')], default='ivyis', max_length=10)),
                ('name', models.CharField(max_length=150)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('mobile_number', models.CharField(max_length=15)),
                ('aadhaar_number', models.CharField(max_length=12)),
                ('driving_licence_number', models.CharField(max_length=30, unique=True)),
                ('dl_type', models.CharField(choices=[('LMV', 'LMV'), ('HMV', 'HMV'), ('LMV_HMV', 'LMV + HMV'), ('TRANSPORT', 'Transport'), ('OTHER', 'Other')], max_length=20)),
                ('dl_issued_date', models.DateField()),
                ('dl_expired_date', models.DateField()),
                ('permanent_address', models.TextField()),
                ('current_address', models.TextField()),
                ('medical_certificate', models.FileField(upload_to='drivers/medical_certificates/')),
                ('police_verification_certificate', models.FileField(upload_to='drivers/police_verification/')),
                ('photo', models.ImageField(upload_to='drivers/photos/')),
                ('aadhaar_front', models.ImageField(upload_to='drivers/aadhaar/')),
                ('aadhaar_back', models.ImageField(upload_to='drivers/aadhaar/')),
                ('dl_front', models.ImageField(upload_to='drivers/driving_license/')),
                ('dl_back', models.ImageField(upload_to='drivers/driving_license/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='drivers', to='Core.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_registration', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'driver_registrations',
                'ordering': ['-created_at'],
            },
        ),
    ]
