# Generated by Django 5.1.6 on 2026-10-07 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0006_driverregistration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverregistration',
            name='user',
        ),
    ]
