# Generated by Django 5.1.6 on 2026-10-07 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0007_remove_driverregistration_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(db_index=True, max_length=15, unique=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_driver', models.BooleanField(default=False)),
                ('is_truckowner', models.BooleanField(default=False)),
                ('is_manufacturer', models.BooleanField(default=False)),
                ('is_transport_vendor', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_roles',
            },
        ),
    ]
