# Generated by Django 5.1.6 on 2026-10-08 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0008_userrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='other_document',
            field=models.FileField(blank=True, null=True, upload_to='company_documents/'),
        ),
    ]
